name: "Picon"
designer: "yne"
designer_url: "https://github.com/yne"
manufacturer: "yne"
manufacturer_url: "https://yne.fr"
license: "OFL"
license_url: "http://scripts.sil.org/OFL"
category: "MONOSPACE"
date_added: "2020-01-20"
description: "Easy Hackable PicoIcon Set"
version: "Version 1.0; git-0000000-release"
fonts {
  name: "Picon"
  style: "normal"
  style_name: "Regular"
  weight: 400
  filename: "Picon-Regular.ttf"
  post_script_name: "Picon-Regular"
  full_name: "Picon Regular"
  copyright: "Copyright 2020 The Picon Project Authors (https://github.com/yne/picon/graphs/contributors with Reserved Font Name \"Picon\")"
  trademark: "Picon (tm)"
}
subsets: "menu"
subsets: "latin"
subsets: "latin-ext"